### PR TITLE
Update discord avatar on login

### PR DESCRIPTION
**Pull request by natehalsey**
I haven't Author/DevQA'd this.

### CODE REVIEW

**Comment by GOATS2K** [comment]
There's absolutely no need to introduce Pydantic here. That'll come with the new FastAPI migration, so I suggest that you just replace the avatar url in the database if it's different than the one that already exists with an UPDATE statement.

**Comment by natehalsey** [comment]
> There's absolutely no need to introduce Pydantic here. That'll come with the new FastAPI migration, so I suggest that you just replace the avatar url in the database if it's different than the one that already exists with an UPDATE statement.

Pydantic has a lot of nice features and goes along well with typing. I can remove it here, but I do recommend it's use. It doesn't have to be based on your overarching goal of FastAPI migration.

**Comment by GOATS2K** [comment]
I'm well aware of that, but it's not needed here, and there's no need to introduce a new dependency for such a trivial bug like this.

**Comment by natehalsey** [comment]
> I'm well aware of that, but it's not needed here, and there's no need to introduce a new dependency for such a trivial bug like this.

Uh just forget it dude. Just trying to help.

**Pull request closed without merging**
